### ISSUE TITLE
Elastic search bug in aggregations queries

### ISSUE THREAD

**Issue by marcelfalliere** [spacedog-io/services#1]
Hello spacedogs,

I would like to query my backend with an SQL something similar to : `select distinct service from user` where service is a string.

I've tried the [terms aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/2.2/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-approximate-counts) like so :

`HTTP POST https://<mybackend>.spacedog.io/1/search/user`

**Request Body**

```
{
    "aggs" : {
        "unique_services" : {
            "terms" : { 
                "field" : "service"
            }
        }
    }
}

```

**Response body**

```
{
  "success": false,
  "status": 500,
  "error": {
    "type": "org.elasticsearch.action.search.SearchPhaseExecutionException",
    "message": "all shards failed",
    "cause": {
      "type": "org.elasticsearch.ElasticsearchException$1",
      "message": "Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value\n at [Source: [B@73cb8326; line: 5, column: 36]",
      "cause": {
        "type": "com.fasterxml.jackson.core.JsonParseException",
        "message": "Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value\n at [Source: [B@73cb8326; line: 5, column: 36]"
      }
    }
  }
}
```

Wouf

**Comment by davattias** [comment]
Reproduced.

Fixed by replacing simple json serialization of aggregations to specific elastic json serialization to make complex state checks work in aggregation model object getters.

Fixed in v0.10.2
