### ISSUE TITLE
[schema endpoint] RFE: "default value" / extensibility concept

### ISSUE THREAD

**Issue by dubo-dubon-duponey** [spacedog-io/services#29]
It should be possible to explicitly declare a default value for a given field (specifically for "required" fields).

Default values don't necessarily *have* to be enforced server-side - they can very well just be used by client-side code as a hint.

Another way to look at this (again, in a purely client-side view) would be to let one attach random meta information to a type, to be interpreted by specific libraries.

```
{
    "myNewType" : {
        "_type" : "object",
        "name" : {
            "_type" : "text",
            "_required": "true",
            "_meta": {
               "com.farcloser.ember::hueponey": "something_that_i_use_client_side_to_enrich_spacedog_types_locally",
               "com.farcloser.ember::defaultValue": "foo bar baz",
               "com.cordova.mobile::foofoo": "barbar"
            }
        }
    }
}
```

This "extension" mechanism would let libraries author experiment with the service and propose extensions that you can later on incorporate when they are fully baked.

wdyt?

**Comment by davattias** [comment]
Agreed. Nice Feature.

2016-06-10 7:58 GMT+02:00 dubo-dubon-duponey <notifications@github.com>:
