### ISSUE TITLE
[share] Content-type should be returned in shares list

### ISSUE THREAD

**Issue by dubo-dubon-duponey** [spacedog-io/services#38]
It's interesting if you want to list shares and present them to the user with visual feedback describing the content-type (or even a preview depending on the content-type)

**Comment by davattias** [comment]
Would be nice but current external file service does not provide an easy way to get this metadata. Low priority.

**Comment by dubo-dubon-duponey** [comment]
Maybe user-defined metadata?

http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html

**Comment by davattias** [comment]
The s3 listObjects method does not return metadata.

**Comment by dubo-dubon-duponey** [comment]
I see. No big deal.

Thanks for clarifying.

**Comment by dubo-dubon-duponey** [comment]
I'm closing this.

For the record, if the implementer wants more "meta" information alongside the shares, he can just create additional objects and store them into the /data endpoint instead.
