### ISSUE TITLE
[share] having the filename in the url is weird and makes it complicated to use

### ISSUE THREAD

**Issue by dubo-dubon-duponey** [spacedog-io/services#39]
Since you give each share a UUID, that should be enough.

If the concern is about the filename when saving from a browser, you can use `Content-disposition` instead I think (https://tools.ietf.org/html/rfc2183#section-2.3).

**Comment by davattias** [comment]
The filename is part of the share UUID to avoid url confusion.

For browser auto save, use the following query param and value `withContentDisposition=true`.
