### ISSUE TITLE
[user] user can be created (POST) with no password

### ISSUE THREAD

**Issue by dubo-dubon-duponey** [spacedog-io/services#49]
(and a reset code is returned)

Not sure if this is intentional or a side-effect (tend to think the later, since this (weirdly) duplicates the behavior of DELETE /password).

**Comment by davattias** [comment]
This is intentional. Admin can create user accounts without any password and provide password reset codes to account recipients.

**Comment by dubo-dubon-duponey** [comment]
Makes sense. Thanks for the clarification.
